"""Initial migration - complete current schema (Clientes, Productos, TipoMercado support, full inventory models)

Revision ID: 7babb607ab51
Revises: 
Create Date: 2026-05-25 16:09:19.490760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7babb607ab51'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('empresa', sa.String(), nullable=True),
    sa.Column('contacto', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('notas', sa.String(), nullable=True),
    sa.Column('activo', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('inventario_campo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variedad', sa.Enum('EARLY_SWEET', 'FLAME', 'SUMMER_ROYAL', name='variedaduva'), nullable=False),
    sa.Column('mercado', sa.Enum('NACIONAL', 'EXPORTACION', name='tipomercado'), nullable=False),
    sa.Column('cantidad_disponible', sa.Integer(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventario_campo_id'), 'inventario_campo', ['id'], unique=False)
    op.create_table('inventario_final',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto', sa.Enum('UVA', name='producto'), nullable=False),
    sa.Column('variedad', sa.Enum('EARLY_SWEET', 'FLAME', 'SUMMER_ROYAL', name='variedaduva'), nullable=False),
    sa.Column('tipo_cultivo', sa.Enum('ORGANICA', 'CONVENCIONAL', name='tipocultivo'), nullable=False),
    sa.Column('mercado', sa.Enum('NACIONAL', 'EXPORTACION', name='tipomercado'), nullable=False),
    sa.Column('cantidad_stock', sa.Integer(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('atributos_extra', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto', 'variedad', 'tipo_cultivo', 'mercado', name='uq_inventario_final_completo')
    )
    op.create_index(op.f('ix_inventario_final_id'), 'inventario_final', ['id'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('activo', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('nombre_completo', sa.String(), nullable=False),
    sa.Column('rol', sa.Enum('RECEPCION_EMPACADOR', 'GERENTE_EMPAQUE', 'DIRECTOR_COMERCIAL', 'OBSERVADOR', name='rol'), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('embarque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_salida', sa.Date(), nullable=True),
    sa.Column('hora_salida', sa.DateTime(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('notas', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embarque_id'), 'embarque', ['id'], unique=False)
    op.create_table('empaque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('producto', sa.Enum('UVA', name='producto'), nullable=False),
    sa.Column('variedad', sa.Enum('EARLY_SWEET', 'FLAME', 'SUMMER_ROYAL', name='variedaduva'), nullable=False),
    sa.Column('tipo_cultivo', sa.Enum('ORGANICA', 'CONVENCIONAL', name='tipocultivo'), nullable=False),
    sa.Column('mercado', sa.Enum('NACIONAL', 'EXPORTACION', name='tipomercado'), nullable=False),
    sa.Column('cantidad_cajas_campo_usadas', sa.Integer(), nullable=False),
    sa.Column('cantidad_cajas_carton_producidas', sa.Integer(), nullable=False),
    sa.Column('porcentaje_merma', sa.Float(), nullable=True),
    sa.Column('notas_merma', sa.String(), nullable=True),
    sa.Column('numero_empacador', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empaque_id'), 'empaque', ['id'], unique=False)
    op.create_table('parrilla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('variedad', sa.Enum('EARLY_SWEET', 'FLAME', 'SUMMER_ROYAL', name='variedaduva'), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parrilla_id'), 'parrilla', ['id'], unique=False)
    op.create_table('recepcion_campo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('hora', sa.DateTime(), nullable=True),
    sa.Column('producto', sa.Enum('UVA', name='producto'), nullable=False),
    sa.Column('variedad', sa.Enum('EARLY_SWEET', 'FLAME', 'SUMMER_ROYAL', name='variedaduva'), nullable=False),
    sa.Column('cantidad_cajas_campo', sa.Integer(), nullable=False),
    sa.Column('cantidad_cajas_carton', sa.Integer(), nullable=True),
    sa.Column('tipo_cultivo_carton', sa.Enum('ORGANICA', 'CONVENCIONAL', name='tipocultivo'), nullable=True),
    sa.Column('mercado', sa.Enum('NACIONAL', 'EXPORTACION', name='tipomercado'), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recepcion_campo_id'), 'recepcion_campo', ['id'], unique=False)
    op.create_table('embarque_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('embarque_id', sa.Integer(), nullable=False),
    sa.Column('producto', sa.Enum('UVA', name='producto'), nullable=False),
    sa.Column('variedad', sa.Enum('EARLY_SWEET', 'FLAME', 'SUMMER_ROYAL', name='variedaduva'), nullable=False),
    sa.Column('tipo_cultivo', sa.Enum('ORGANICA', 'CONVENCIONAL', name='tipocultivo'), nullable=False),
    sa.Column('mercado', sa.Enum('NACIONAL', 'EXPORTACION', name='tipomercado'), nullable=False),
    sa.Column('cantidad_cajas', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['embarque_id'], ['embarque.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embarque_detalle_id'), 'embarque_detalle', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embarque_detalle_id'), table_name='embarque_detalle')
    op.drop_table('embarque_detalle')
    op.drop_index(op.f('ix_recepcion_campo_id'), table_name='recepcion_campo')
    op.drop_table('recepcion_campo')
    op.drop_index(op.f('ix_parrilla_id'), table_name='parrilla')
    op.drop_table('parrilla')
    op.drop_index(op.f('ix_empaque_id'), table_name='empaque')
    op.drop_table('empaque')
    op.drop_index(op.f('ix_embarque_id'), table_name='embarque')
    op.drop_table('embarque')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_inventario_final_id'), table_name='inventario_final')
    op.drop_table('inventario_final')
    op.drop_index(op.f('ix_inventario_campo_id'), table_name='inventario_campo')
    op.drop_table('inventario_campo')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
